import { describe, expect, it } from "vitest";
import { simulate, findFireAge, type FireAgeInputs } from "../fire-age";

// Base scenario = the source HTML's own UI defaults, so these tests are checked
// against the exact same inputs a real user would see on first load.
// Golden values generated by running the original engine functions verbatim in Node.
const defaultInputs: FireAgeInputs = {
  currentAge: 32,
  lifeExpectancy: 80,
  inflation: 0.02,
  salary0: 70000,
  cash0: 15000,
  cashReturn: 0.005,
  bufferMonths: 12,
  isa0: 25000,
  gia0: 8000,
  allocMode: "auto",
  isaAllowance: 20000,
  isaContribM: 0,
  giaContribM: 0,
  pension0: 40000,
  pensionContribM: 400,
  pensionAccess: 57,
  salSacrifice: false,
  spend0: 30000,
  careAge: 70,
  careRate: 0.02,
  hasProperty: true,
  propValue0: 350000,
  mortgageBal0: 250000,
  mortgageRate: 0.045,
  mortgageTerm: 25,
  propAppreciation: 0.01,
  spOn: true,
  spAge: 67,
  spAmount0: 11500,
  eqOn: false,
  eqShares: 0,
  eqPrice: 0,
  eqFutureOn: false,
  eqFutureAnnual0: 0,
  eqFutureYears: 0,
  eqGrowth: 0.06,
  eqMode: "atRetirement",
  eqGradualPct: 0.25,
  growth: 0.065,
  pensionGrowth: 0.065,
};

describe("findFireAge — default scenario", () => {
  it("finds age 56 as the earliest survivable retirement age", () => {
    const { age } = findFireAge(defaultInputs, false);
    expect(age).toBe(56);
  });

  it("row 0 (age 32) is undeflated (y=0) and matches source defaults plus one year of contribution", () => {
    const { result } = findFireAge(defaultInputs, false);
    const first = result!.rows[0];
    expect(first.age).toBe(32);
    expect(first.cash).toBeCloseTo(15000, 2);
    expect(first.isa).toBeCloseTo(25000, 2);
    expect(first.gia).toBeCloseTo(8000, 2);
    expect(first.pension).toBeCloseTo(44800, 2); // 40000 + 400*12
    expect(first.propertyEquity).toBeCloseTo(100000, 2); // 350000 - 250000
  });

  it("the retirement-year row has the expected implied SWR", () => {
    const { age, result } = findFireAge(defaultInputs, false);
    const retiredRow = result!.rows.find((r) => r.age === age);
    expect(retiredRow).toBeDefined();
    expect(result!.impliedSWR).toBeCloseTo(0.08957547109318294, 6);
  });
});

describe("simulate — decumulation waterfall + illiquid backstop", () => {
  it("retiring too early at 45 depletes liquid assets by 46 without property", () => {
    const result = simulate(defaultInputs, 45, false);
    expect(result.survived).toBe(false);
    expect(result.depletionAge).toBe(46);
  });

  it("including property as a last-resort draw extends survival to 68, tapping property", () => {
    const result = simulate(defaultInputs, 45, true);
    expect(result.survived).toBe(false);
    expect(result.depletionAge).toBe(68);
    expect(result.propertyTapped).toBe(true);
  });
});

describe("simulate — pension access-age locking", () => {
  it("pension compounds untouched through age 56, then draws down starting exactly at 57", () => {
    const inp: FireAgeInputs = { ...defaultInputs, currentAge: 45, pensionAccess: 57 };
    const result = simulate(inp, 50, false);
    const at = (age: number) => result.rows.find((r) => r.age === age)!.pension;

    expect(at(50)).toBeCloseTo(77006.80241038358, 4);
    // Still compounding, no draws, right up to (but not including) access age.
    expect(at(56)).toBeCloseTo(99775.91206741068, 4);
    expect(at(56)).toBeGreaterThan(at(50));
    // Access age hits — balance drops because draws are now permitted.
    expect(at(57)).toBeCloseTo(61029.68707178267, 4);
    expect(at(57)).toBeLessThan(at(56));
    expect(at(58)).toBeCloseTo(20831.875747312046, 4);
  });
});

describe("simulate — equity module, all 3 cash-out modes", () => {
  const eqBase: FireAgeInputs = {
    ...defaultInputs,
    currentAge: 40,
    eqOn: true,
    eqShares: 200,
    eqPrice: 50,
    eqGrowth: 0.06,
    eqFutureOn: false,
  };

  it("'atRetirement' mode holds equity untouched, then liquidates it entirely in the retirement year", () => {
    const result = simulate({ ...eqBase, eqMode: "atRetirement" }, 50, false);
    const age49 = result.rows.find((r) => r.age === 49)!;
    const age50 = result.rows.find((r) => r.age === 50)!;
    expect(age49.equity).toBeCloseTo(16726.776482334444, 4);
    expect(age50.equity).toBe(0);
    expect(age50.gia).toBeCloseTo(2610.609020437142, 4);
  });

  it("'gradual' mode sells a fixed fraction of held equity every working year", () => {
    const result = simulate({ ...eqBase, eqMode: "gradual", eqGradualPct: 0.25 }, 50, false);
    const age41 = result.rows.find((r) => r.age === 41)!;
    const age45 = result.rows.find((r) => r.age === 45)!;
    expect(age41.equity).toBeCloseTo(5955.8823529411775, 4);
    expect(age45.equity).toBeCloseTo(2368.5660444150376, 4);
  });

  it("'hold' mode never force-sells during working years (retirement decumulation may still draw it)", () => {
    const result = simulate({ ...eqBase, eqMode: "hold" }, 50, false);
    const age50 = result.rows.find((r) => r.age === 50)!;
    expect(age50.equity).toBeCloseTo(4682.308407194522, 4);
  });
});
