import { describe, expect, it } from "vitest";
import { simulate, findFireAge, type FireAgeInputs } from "../fire-age";
import { calcTax, incomeTaxOnly, grossUpTaxableWithdrawal } from "../tax";

// Base scenario = the source HTML's own UI defaults, so these tests are checked
// against the exact same inputs a real user would see on first load.
// Golden values generated by running the original engine functions verbatim in Node.
const defaultInputs: FireAgeInputs = {
  currentAge: 32,
  lifeExpectancy: 80,
  inflation: 0.02,
  salary0: 70000,
  cash0: 15000,
  cashReturn: 0.005,
  bufferMonths: 12,
  isa0: 25000,
  gia0: 8000,
  lisa0: 0,
  lisaContribM: 0,
  allocMode: "auto",
  isaAllowance: 20000,
  isaContribM: 0,
  giaContribM: 0,
  pension0: 40000,
  pensionContribM: 400,
  pensionAccess: 57,
  salSacrifice: false,
  spend0: 30000,
  careAge: 70,
  careRate: 0.02,
  hasProperty: true,
  propValue0: 350000,
  mortgageBal0: 250000,
  mortgageRate: 0.045,
  mortgageTerm: 25,
  propAppreciation: 0.01,
  spOn: true,
  spAge: 67,
  spAmount0: 11500,
  dbPensionOn: false,
  dbPensionAnnual0: 0,
  dbPensionNormalAge: 65,
  dbPensionReductionRate: 0.05,
  coupleMode: false,
  partnerSalary0: 0,
  partnerPension0: 0,
  partnerPensionContribM: 0,
  partnerPensionAccess: 57,
  partnerSalSacrifice: false,
  partnerDbPensionOn: false,
  partnerDbPensionAnnual0: 0,
  partnerDbPensionNormalAge: 65,
  partnerDbPensionReductionRate: 0.05,
  eqOn: false,
  eqShares: 0,
  eqPrice: 0,
  eqFutureOn: false,
  eqFutureAnnual0: 0,
  eqFutureYears: 0,
  eqGrowth: 0.06,
  eqMode: "atRetirement",
  eqGradualPct: 0.25,
  growth: 0.065,
  pensionGrowth: 0.065,
};

describe("findFireAge — default scenario", () => {
  it("finds age 64 as the earliest retirement age that both survives and stays within the safe withdrawal-rate ceiling", () => {
    // Age 56 technically survives on this one deterministic path, but only at an implied
    // ~8.96% first-year withdrawal rate — more than double the 4% safety ceiling. 64 is the
    // earliest age where survival isn't just a coincidence of the single path modelled.
    const { age } = findFireAge(defaultInputs, false);
    expect(age).toBe(64);
  });

  it("row 0 (age 32) is undeflated (y=0) and matches source defaults plus one year of contribution", () => {
    const { result } = findFireAge(defaultInputs, false);
    const first = result!.rows[0];
    expect(first.age).toBe(32);
    expect(first.cash).toBeCloseTo(15000, 2);
    expect(first.isa).toBeCloseTo(25000, 2);
    expect(first.gia).toBeCloseTo(8000, 2);
    expect(first.pension).toBeCloseTo(44800, 2); // 40000 + 400*12
    expect(first.propertyEquity).toBeCloseTo(100000, 2); // 350000 - 250000
  });

  it("the retirement-year row has the expected implied SWR, at or under the safety ceiling", () => {
    const { age, result } = findFireAge(defaultInputs, false);
    const retiredRow = result!.rows.find((r) => r.age === age);
    expect(retiredRow).toBeDefined();
    expect(result!.impliedSWR).toBeCloseTo(0.03930344057792172, 6);
    expect(result!.impliedSWR).toBeLessThanOrEqual(0.04);
  });

  it("returns null when no age in range clears both the survival and SWR-ceiling bars", () => {
    // A much shorter accumulation window with the same spend leaves no safe age
    // before the search range runs out.
    const tightInputs: FireAgeInputs = { ...defaultInputs, currentAge: 55, lifeExpectancy: 90 };
    const { age, result } = findFireAge(tightInputs, false);
    expect(age).toBeNull();
    expect(result).toBeNull();
  });
});

describe("simulate — decumulation waterfall + illiquid backstop", () => {
  it("retiring too early at 45 depletes liquid assets by 46 without property", () => {
    const result = simulate(defaultInputs, 45, false);
    expect(result.survived).toBe(false);
    expect(result.depletionAge).toBe(46);
  });

  it("including property as a last-resort draw extends survival to 66, tapping property", () => {
    // 68 before pension drawdown was taxed; now that pension withdrawals beyond the 25%
    // tax-free element are grossed up for income tax (see grossUpTaxableWithdrawal in
    // tax.ts), the pension pot empties two years sooner, so the property backstop gets
    // tapped two years earlier too.
    const result = simulate(defaultInputs, 45, true);
    expect(result.survived).toBe(false);
    expect(result.depletionAge).toBe(66);
    expect(result.propertyTapped).toBe(true);
  });
});

describe("simulate — pension access-age locking", () => {
  it("pension compounds untouched through age 56, then draws down starting exactly at 57", () => {
    const inp: FireAgeInputs = { ...defaultInputs, currentAge: 45, pensionAccess: 57 };
    const result = simulate(inp, 50, false);
    const at = (age: number) => result.rows.find((r) => r.age === age)!.pension;

    expect(at(50)).toBeCloseTo(77006.80241038358, 4);
    // Still compounding, no draws, right up to (but not including) access age.
    expect(at(56)).toBeCloseTo(99775.91206741068, 4);
    expect(at(56)).toBeGreaterThan(at(50));
    // Access age hits — balance drops because draws are now permitted. Lower than the
    // pre-tax-fix golden (61029.69): 75% of each withdrawal beyond the 25% tax-free element
    // is now taxed as income (grossUpTaxableWithdrawal in tax.ts), so the pot has to yield a
    // bigger gross withdrawal to net the same required spend, depleting it faster.
    expect(at(57)).toBeCloseTo(55747.40039299883, 4);
    expect(at(57)).toBeLessThan(at(56));
    expect(at(58)).toBeCloseTo(10034.028350616152, 4);
  });
});

describe("simulate — equity module, all 3 cash-out modes", () => {
  const eqBase: FireAgeInputs = {
    ...defaultInputs,
    currentAge: 40,
    eqOn: true,
    eqShares: 200,
    eqPrice: 50,
    eqGrowth: 0.06,
    eqFutureOn: false,
  };

  it("'atRetirement' mode holds equity untouched, then liquidates it entirely in the retirement year", () => {
    const result = simulate({ ...eqBase, eqMode: "atRetirement" }, 50, false);
    const age49 = result.rows.find((r) => r.age === 49)!;
    const age50 = result.rows.find((r) => r.age === 50)!;
    expect(age49.equity).toBeCloseTo(16726.776482334444, 4);
    expect(age50.equity).toBe(0);
    expect(age50.gia).toBeCloseTo(2610.609020437142, 4);
  });

  it("'gradual' mode sells a fixed fraction of held equity every working year", () => {
    const result = simulate({ ...eqBase, eqMode: "gradual", eqGradualPct: 0.25 }, 50, false);
    const age41 = result.rows.find((r) => r.age === 41)!;
    const age45 = result.rows.find((r) => r.age === 45)!;
    expect(age41.equity).toBeCloseTo(5955.8823529411775, 4);
    expect(age45.equity).toBeCloseTo(2368.5660444150376, 4);
  });

  it("'hold' mode never force-sells during working years (retirement decumulation may still draw it)", () => {
    const result = simulate({ ...eqBase, eqMode: "hold" }, 50, false);
    const age50 = result.rows.find((r) => r.age === 50)!;
    expect(age50.equity).toBeCloseTo(4682.308407194522, 4);
  });
});

describe("simulate — LISA", () => {
  const lisaBase: FireAgeInputs = {
    ...defaultInputs,
    currentAge: 40,
    lisa0: 0,
    growth: 0,
    inflation: 0,
  };

  it("earns the 25% government bonus in full when the annual contribution is under the £4,000 cap", () => {
    // £300/mo * 12 = £3,600/yr, under the cap — full 25% bonus applies: 3600 * 1.25 = 4500.
    const result = simulate({ ...lisaBase, lisaContribM: 300 }, 65, false);
    expect(result.rows[0].lisa).toBeCloseTo(4500, 4);
  });

  it("caps the bonus at the £4,000 annual contribution limit — excess still goes in, just unbonused", () => {
    // £500/mo * 12 = £6,000/yr, over the cap. Bonus is 4000 * 0.25 = 1000, not 6000 * 0.25.
    // Full contribution still lands in the account: 6000 + 1000 = 7000.
    const result = simulate({ ...lisaBase, lisaContribM: 500 }, 65, false);
    expect(result.rows[0].lisa).toBeCloseTo(7000, 4);
  });

  it("stops accepting new contributions (and the bonus) from age 50 onward", () => {
    const result = simulate({ ...lisaBase, currentAge: 48, lisaContribM: 300 }, 65, false);
    const at = (age: number) => result.rows.find((r) => r.age === age)!.lisa;
    // Ages 48 and 49: contribution + bonus keeps landing (growth is 0, so purely additive).
    expect(at(48)).toBeCloseTo(4500, 4); // 3600 + 900
    expect(at(49)).toBeCloseTo(9000, 4); // + another 3600 + 900
    // Age 50 onward: no new contribution or bonus — balance is flat (0% growth).
    expect(at(50)).toBeCloseTo(9000, 4);
    expect(at(55)).toBeCloseTo(9000, 4);
  });

  it("is not touched by decumulation before age 60, even once every other liquid pot is exhausted", () => {
    const tightInputs: FireAgeInputs = {
      ...lisaBase,
      currentAge: 55,
      lisa0: 50000,
      lisaContribM: 0,
      cash0: 5000,
      isa0: 0,
      gia0: 0,
      pension0: 0,
      pensionContribM: 0,
      hasProperty: false,
      spOn: false,
      spend0: 20000,
    };
    // Retiring at 55: cash (£5,000) covers only a quarter of one year's spend, and every
    // other pot is empty — LISA holds £50,000 but can't be touched until 60, so the plan
    // should not survive despite the LISA balance being more than enough on its own.
    const lockedResult = simulate(tightInputs, 55, false);
    expect(lockedResult.survived).toBe(false);
    expect(lockedResult.rows.find((r) => r.age === 55)!.lisa).toBeCloseTo(50000, 4);

    // The same scenario, but retiring at 60 instead (and only needing to cover a short
    // 2-year retirement window) — LISA is now unlocked from day one and comfortably
    // covers the shortfall.
    const unlockedResult = simulate(
      { ...tightInputs, currentAge: 60, lifeExpectancy: 61 },
      60,
      false,
    );
    expect(unlockedResult.survived).toBe(true);
    expect(unlockedResult.rows.find((r) => r.age === 60)!.lisa).toBeLessThan(50000);
  });
});

describe("simulate — DB (defined benefit) pension", () => {
  const dbBase: FireAgeInputs = {
    ...defaultInputs,
    currentAge: 55,
    pensionAccess: 55,
    inflation: 0,
    growth: 0,
    pensionGrowth: 0,
    spOn: false,
    dbPensionOn: true,
    dbPensionAnnual0: 10000,
    dbPensionNormalAge: 65,
    dbPensionReductionRate: 0.05,
  };

  it("pays nothing when dbPensionOn is off, even with an annual amount set", () => {
    const result = simulate({ ...dbBase, dbPensionOn: false }, 55, false);
    expect(result.rows.find((r) => r.age === 55)!.dbPensionPaid).toBe(0);
  });

  it("pays the full amount, unreduced, when claimed at or after the scheme's normal pension age", () => {
    const result = simulate({ ...dbBase, currentAge: 65 }, 65, false);
    expect(result.rows.find((r) => r.age === 65)!.dbPensionPaid).toBeCloseTo(10000, 4);
    // A year past normal age doesn't earn a bonus in this simplified model — still full amount.
    const later = simulate({ ...dbBase, currentAge: 65, lifeExpectancy: 90 }, 65, false);
    expect(later.rows.find((r) => r.age === 66)!.dbPensionPaid).toBeCloseTo(10000, 4);
  });

  it("reduces the annual amount by the reduction rate for each year claimed before normal age", () => {
    // Retiring/claiming at 55, 10 years before normal age 65, at 5%/yr: 10000 * (1 - 0.5) = 5000.
    const result = simulate(dbBase, 55, false);
    expect(result.rows.find((r) => r.age === 55)!.dbPensionPaid).toBeCloseTo(5000, 4);
    // Five years later (age 60), 5 years early: 10000 * (1 - 0.25) = 7500.
    expect(result.rows.find((r) => r.age === 60)!.dbPensionPaid).toBeCloseTo(7500, 4);
  });

  it("directly reduces how much needs to be drawn from other pots", () => {
    const withDb = simulate(dbBase, 55, false);
    const withoutDb = simulate({ ...dbBase, dbPensionOn: false }, 55, false);
    const isaAt55 = (r: typeof withDb) => r.rows.find((row) => row.age === 55)!.isa;
    // Same starting ISA balance, same spend, no growth — the DB pension should leave
    // strictly more in the ISA in the very first retired year, since it's covering
    // part of spend directly instead of that shortfall being drawn from savings.
    expect(isaAt55(withDb)).toBeGreaterThan(isaAt55(withoutDb));
  });
});

describe("simulate — couple mode", () => {
  const coupleBase: FireAgeInputs = {
    ...defaultInputs,
    currentAge: 40,
    inflation: 0,
    growth: 0,
    pensionGrowth: 0,
    spOn: false,
    coupleMode: true,
    partnerSalary0: 50000,
    partnerPension0: 10000,
    partnerPensionContribM: 300,
    partnerPensionAccess: 60,
    partnerSalSacrifice: false,
    partnerDbPensionOn: false,
    partnerDbPensionAnnual0: 0,
    partnerDbPensionNormalAge: 65,
    partnerDbPensionReductionRate: 0.05,
  };

  it("ignores every partner field entirely when coupleMode is off", () => {
    const withCoupleDataOff = simulate({ ...coupleBase, coupleMode: false }, 70, false);
    const noPartnerDataAtAll = simulate(
      { ...defaultInputs, currentAge: 40, inflation: 0, growth: 0, pensionGrowth: 0, spOn: false },
      70,
      false,
    );
    const row = (r: typeof withCoupleDataOff, age: number) => r.rows.find((x) => x.age === age)!;
    expect(row(withCoupleDataOff, 41).total).toBeCloseTo(row(noPartnerDataAtAll, 41).total, 4);
    expect(row(withCoupleDataOff, 41).partnerPension).toBe(0);
  });

  it("accrues the partner's own pension contributions independently of the primary pension", () => {
    const result = simulate(coupleBase, 70, false);
    const at = (age: number) => result.rows.find((r) => r.age === age)!;
    // Contributions apply from the starting year too (y=0), matching the existing
    // convention for the primary pension (see "row 0 ... plus one year of contribution"
    // above): £10,000 + £300/mo * 12 = £13,600 at age 40 itself.
    expect(at(40).partnerPension).toBeCloseTo(13600, 4);
    // A second working year adds another £3,600.
    expect(at(41).partnerPension).toBeCloseTo(17200, 4);
    // Primary pension (defaultInputs: £40,000 + £400/mo*12) is unaffected by the partner's numbers.
    expect(at(40).pension).toBeCloseTo(44800, 4);
  });

  it("adds the partner's take-home pay into household surplus, growing savings faster than solo", () => {
    const withPartner = simulate(coupleBase, 70, false);
    const soloOnly = simulate({ ...coupleBase, coupleMode: false }, 70, false);
    const isaAt41 = (r: typeof withPartner) => r.rows.find((row) => row.age === 41)!.isa;
    expect(isaAt41(withPartner)).toBeGreaterThan(isaAt41(soloOnly));
  });

  it("doesn't draw the partner's pension before the partner's own access age, even once other pots are empty", () => {
    const tight: FireAgeInputs = {
      ...coupleBase,
      currentAge: 58,
      lifeExpectancy: 62,
      salary0: 0,
      pensionContribM: 0,
      partnerPensionContribM: 0,
      cash0: 1000,
      isa0: 0,
      gia0: 0,
      pension0: 0,
      spend0: 20000,
      partnerPensionAccess: 60,
      partnerPension0: 50000,
    };
    // Retiring at 58: partner's pension access age (60) hasn't been reached yet, every
    // other pot is nearly empty, so the plan shouldn't survive despite £50k sitting in
    // the partner's pension.
    const result = simulate(tight, 58, false);
    expect(result.survived).toBe(false);
    expect(result.rows.find((r) => r.age === 58)!.partnerPension).toBeCloseTo(50000, 4);
  });

  it("pays the partner's DB pension once retired and past their access age, reduced for early claiming", () => {
    const result = simulate(
      {
        ...coupleBase,
        partnerDbPensionOn: true,
        partnerDbPensionAnnual0: 8000,
        partnerDbPensionNormalAge: 65,
        partnerDbPensionReductionRate: 0.05,
      },
      60,
      false,
    );
    // Retired at 60, partner's pension access age is 60 (coupleBase), 5 years before
    // partner's DB normal age of 65: 8000 * (1 - 0.05*5) = 6000.
    expect(result.rows.find((r) => r.age === 60)!.partnerDbPensionPaid).toBeCloseTo(6000, 4);
    // Primary DB pension is untouched by the partner's numbers (off by default in coupleBase).
    expect(result.rows.find((r) => r.age === 60)!.dbPensionPaid).toBe(0);
  });

  it("partner DB pension directly reduces how much needs to be drawn from other pots", () => {
    const tight: FireAgeInputs = {
      ...coupleBase,
      currentAge: 60,
      salary0: 0,
      pensionContribM: 0,
      partnerPensionContribM: 0,
      cash0: 2000,
      isa0: 20000,
      gia0: 0,
      pension0: 0,
      partnerPension0: 0,
      spend0: 20000,
      partnerPensionAccess: 60,
      hasProperty: false,
    };
    const withPartnerDb = simulate(
      { ...tight, partnerDbPensionOn: true, partnerDbPensionAnnual0: 8000, partnerDbPensionNormalAge: 60 },
      60,
      false,
    );
    const withoutPartnerDb = simulate({ ...tight, partnerDbPensionOn: false }, 60, false);
    const isaAt60 = (r: typeof withPartnerDb) => r.rows.find((row) => row.age === 60)!.isa;
    expect(isaAt60(withPartnerDb)).toBeGreaterThan(isaAt60(withoutPartnerDb));
  });
});

describe("simulate — tax/NI breakdown row fields", () => {
  it("matches calcTax exactly for a solo working year", () => {
    const result = simulate(defaultInputs, 56, false);
    const row = result.rows.find((r) => r.age === defaultInputs.currentAge)!;
    // Salary sacrifice is off in defaultInputs, so taxable salary is the full gross.
    const expected = calcTax(defaultInputs.salary0);
    expect(row.grossIncome).toBeCloseTo(defaultInputs.salary0, 2);
    expect(row.incomeTax).toBeCloseTo(expected.tax, 2);
    expect(row.nationalInsurance).toBeCloseTo(expected.ni, 2);
    expect(row.takeHomePay).toBeCloseTo(expected.takeHome, 2);
  });

  it("is entirely zero once retired — salary stops, this isn't DB/State Pension income", () => {
    const result = simulate(defaultInputs, 56, false);
    const row = result.rows.find((r) => r.age === 60)!;
    expect(row.grossIncome).toBe(0);
    expect(row.incomeTax).toBe(0);
    expect(row.nationalInsurance).toBe(0);
    expect(row.takeHomePay).toBe(0);
  });

  it("sums both partners' gross income, tax, and NI independently in couple mode", () => {
    const coupleInputs: FireAgeInputs = {
      ...defaultInputs,
      coupleMode: true,
      partnerSalary0: 45000,
      partnerPension0: 0,
      partnerPensionContribM: 0,
      partnerPensionAccess: 57,
      partnerSalSacrifice: false,
    };
    const result = simulate(coupleInputs, 56, false);
    const row = result.rows.find((r) => r.age === defaultInputs.currentAge)!;
    const primaryTax = calcTax(defaultInputs.salary0);
    const partnerTax = calcTax(45000);
    expect(row.grossIncome).toBeCloseTo(defaultInputs.salary0 + 45000, 2);
    expect(row.incomeTax).toBeCloseTo(primaryTax.tax + partnerTax.tax, 2);
    expect(row.nationalInsurance).toBeCloseTo(primaryTax.ni + partnerTax.ni, 2);
    expect(row.takeHomePay).toBeCloseTo(primaryTax.takeHome + partnerTax.takeHome, 2);
  });
});

describe("simulate — tax on retirement drawdown", () => {
  it("pension withdrawals beyond the 25% tax-free element are taxed as income, grossed up to meet spend", () => {
    const inp: FireAgeInputs = {
      ...defaultInputs,
      currentAge: 57,
      lifeExpectancy: 58,
      inflation: 0,
      growth: 0,
      pensionGrowth: 0,
      cash0: 0,
      isa0: 0,
      gia0: 0,
      lisa0: 0,
      pension0: 1_000_000,
      pensionContribM: 0,
      pensionAccess: 57,
      spend0: 20000,
      hasProperty: false,
      spOn: false,
      dbPensionOn: false,
    };
    const result = simulate(inp, 57, false);
    const { drawn } = grossUpTaxableWithdrawal(1_000_000, 20000, 0, 0.25);
    const row = result.rows.find((r) => r.age === 57)!;
    // Gross withdrawal is bigger than the £20,000 actually needed — part of it goes to tax
    // rather than being pound-for-pound spendable, unlike before this fix.
    expect(drawn).toBeGreaterThan(20000);
    expect(row.pension).toBeCloseTo(1_000_000 - drawn, 2);
  });

  it("DB pension is taxed before it offsets required spend, so it covers less than its gross amount would suggest", () => {
    const base: FireAgeInputs = {
      ...defaultInputs,
      currentAge: 55,
      lifeExpectancy: 56,
      inflation: 0,
      growth: 0,
      pensionGrowth: 0,
      cash0: 0,
      isa0: 100000,
      gia0: 0,
      lisa0: 0,
      pension0: 0,
      pensionContribM: 0,
      pensionAccess: 55,
      hasProperty: false,
      spOn: false,
      dbPensionOn: true,
      dbPensionAnnual0: 20000,
      dbPensionNormalAge: 55,
      dbPensionReductionRate: 0.05,
      // £19,000 sits between the DB pension's gross (£20,000) and its net-of-tax amount
      // (£20,000 - incomeTaxOnly(£20,000).tax = £18,514: £7,430 taxable above the personal
      // allowance at 20% = £1,486 tax), so whether the model taxes the DB pension changes
      // whether anything needs to be drawn from the ISA at all.
      spend0: 19000,
    };
    const result = simulate(base, 55, false);
    const row = result.rows.find((r) => r.age === 55)!;
    const netDb = 20000 - incomeTaxOnly(20000).tax;
    expect(netDb).toBeCloseTo(18514, 2);
    // dbPensionPaid still reports the gross amount the scheme actually pays out.
    expect(row.dbPensionPaid).toBeCloseTo(20000, 2);
    // But required spend is only reduced by the net (post-tax) amount, so £486 of spend
    // (19000 - 18514) still has to come out of the ISA — it would've been £0 pre-fix.
    expect(row.isa).toBeCloseTo(100000 - 486, 2);
  });
});
