import { describe, expect, it } from "vitest";
import { mortgageBalanceAt, projectPath, calcFireNumber, type FireNumberInputs } from "../fire-number";
import { grossUpTaxableWithdrawal } from "../tax";

// Golden values generated by running the original engine functions verbatim in Node.
describe("mortgageBalanceAt", () => {
  it.each([
    [0, 250000],
    [1, 244461.72506717968],
    [5, 219644.75855609318],
    [10, 181646.19418560824],
    [24.9, 1384.3897333956334],
    [25, 0],
    [30, 0], // past term
  ])("yearsElapsed=%s -> balance=%f", (yearsElapsed, balance) => {
    expect(mortgageBalanceAt(250000, 0.045, 25, yearsElapsed)).toBeCloseTo(balance, 4);
  });
});

describe("projectPath — lump vs. gradual debt clearing", () => {
  const args = [60000, 30000, 500, 32, 50, 90, 0.045, 30000, 40000] as const;

  it("lump mode shows a visible step-down in liquid balance at retirement age", () => {
    const result = projectPath(...args, 0, 57, "lump", 0);
    const age49 = result.rows.find((r) => r.age === 49)!.liquid;
    const age50 = result.rows.find((r) => r.age === 50)!.liquid;
    expect(age49).toBeCloseTo(278290.3034104501, 4);
    expect(age50).toBeCloseTo(256936.13359361497, 4);
    expect(age50).toBeLessThan(age49); // the lump-sum debt-clearing dip
    // 65 before pension drawdown was taxed; now that pension withdrawals beyond the 25%
    // tax-free element are grossed up for income tax (grossUpTaxableWithdrawal in tax.ts),
    // the pot has to yield more gross to cover the same spend, so it empties a year sooner.
    expect(result.depletionAge).toBe(65);
  });

  it("gradual mode shows no dip at retirement, instead a straight-line drag afterward", () => {
    const result = projectPath(...args, 0, 57, "gradual", 15);
    const age50 = result.rows.find((r) => r.age === 50)!.liquid;
    const age51 = result.rows.find((r) => r.age === 51)!.liquid;
    expect(age50).toBeCloseTo(296936.13359361497, 4);
    expect(result.depletionAge).toBe(66);
    expect(age51).toBeCloseTo(277631.59293866094, 4);
  });

  it("lump vs. gradual are NOT accidentally equivalent — a tighter scenario diverges in depletion age", () => {
    const lump = projectPath(20000, 10000, 200, 40, 55, 90, 0.03, 25000, 60000, 0, 57, "lump", 0);
    const gradual = projectPath(20000, 10000, 200, 40, 55, 90, 0.03, 25000, 60000, 0, 57, "gradual", 20);
    expect(lump.depletionAge).toBe(56);
    expect(gradual.depletionAge).toBe(59);
    expect(gradual.depletionAge).not.toBe(lump.depletionAge);
  });

  it("pension is untouched (still compounding, no draws) before pensionAccessAge", () => {
    const result = projectPath(0, 30000, 0, 50, 50, 90, 0.045, 20000, 0, 0, 57, "lump", 0);
    const age56 = result.rows.find((r) => r.age === 56)!.pension;
    const age50 = result.rows.find((r) => r.age === 50)!.pension;
    expect(age56).toBeGreaterThan(age50); // pure compounding, no draws yet
  });

  it("pension withdrawals beyond the 25% tax-free element are taxed as income, grossed up to meet spend", () => {
    const result = projectPath(0, 1_000_000, 0, 57, 57, 58, 0, 20000, 0, 0, 57, "lump", 0);
    const { drawn } = grossUpTaxableWithdrawal(1_000_000, 20000, 0, 0.25);
    const age58 = result.rows.find((r) => r.age === 58)!.pension;
    // Gross withdrawal is bigger than the £20,000 actually needed — part of it goes to tax
    // rather than being pound-for-pound spendable, unlike before this fix.
    expect(drawn).toBeGreaterThan(20000);
    expect(age58).toBeCloseTo(1_000_000 - drawn, 2);
  });
});

describe("calcFireNumber — verdict transitions as spend increases", () => {
  const base: FireNumberInputs = {
    currentAge: 32,
    retireAge: 50,
    lifeExpectancy: 90,
    spend: 20000,
    hasDebt: false,
    debtToday: 0,
    debtRate: 0.045,
    debtTerm: 0,
    debtMode: "lump",
    cash: 20000,
    isa: 40000,
    gia: 10000,
    pension: 30000,
    growth: 0.045,
    swr: 0.035,
    hasProperty: false,
    property: 0,
    propGrowth: 0.01,
  };

  it("low spend relative to assets is on track without saving anything more", () => {
    const result = calcFireNumber({ ...base, spend: 12000 });
    expect(result.verdict.kind).toBe("onTrack");
  });

  it("moderate spend needs a recommended monthly saving to stay on track", () => {
    const result = calcFireNumber({ ...base, spend: 45000 });
    expect(result.verdict.kind).toBe("saveToFix");
    expect(result.monthlySaving).toBeGreaterThan(0);
  });

  it("a long post-retirement horizon with no growth outlives even the SWR-sized, recommended-saving pot", () => {
    // With growth=0, a pot sized at spend/swr only lasts 1/swr years of flat drawdown
    // (~28.6yrs at swr=0.035) — a horizon longer than that runs out regardless of saving.
    const result = calcFireNumber({
      ...base,
      growth: 0,
      pension: 0,
      spend: 40000,
      lifeExpectancy: 95, // retireAge 50 -> 45-year horizon, well past ~28.6yrs
    });
    expect(result.verdict.kind).toBe("short");
  });

  it("computes property-inclusive paths only when a property is set", () => {
    const withoutProp = calcFireNumber(base);
    expect(withoutProp.usingProperty).toBe(false);
    expect(withoutProp.paths.noSaveWithProp).toBeNull();
    expect(withoutProp.paths.saveWithProp).toBeNull();

    const withProp = calcFireNumber({ ...base, hasProperty: true, property: 300000 });
    expect(withProp.usingProperty).toBe(true);
    expect(withProp.paths.noSaveWithProp).not.toBeNull();
    expect(withProp.paths.saveWithProp).not.toBeNull();
  });

  it("debtAtRetirement is projected forward from today's balance via mortgageBalanceAt", () => {
    const result = calcFireNumber({
      ...base,
      hasDebt: true,
      debtToday: 250000,
      debtRate: 0.045,
      debtTerm: 25,
    });
    // yearsToRetirement = 50-32 = 18
    expect(result.debtAtRetirement).toBeCloseTo(mortgageBalanceAt(250000, 0.045, 25, 18), 4);
  });
});
