import { describe, expect, it } from "vitest";
import {
  calcTax,
  marginalTaxOnExtra,
  incomeTaxOnly,
  marginalIncomeTaxOnly,
  grossUpTaxableWithdrawal,
} from "../tax";

// Golden values generated by running the original uk_fire_calculator.html engine
// functions verbatim in Node — see plan for methodology.
describe("calcTax", () => {
  it.each([
    [0, 0, 0, 0],
    [10000, 0, 0, 10000],
    [12570, 0, 0, 12570],
    [30000, 3486, 1394.4, 25119.6],
    [70000, 15432, 3410.6, 51157.4],
    [100000, 27432, 4010.6, 68557.4],
    [125140, 40002, 4513.4, 80624.6],
    [150000, 51189, 5010.6, 93800.4],
  ])("gross=%i -> tax=%f, ni=%f, takeHome=%f", (gross, tax, ni, takeHome) => {
    const result = calcTax(gross);
    expect(result.tax).toBeCloseTo(tax, 2);
    expect(result.ni).toBeCloseTo(ni, 2);
    expect(result.takeHome).toBeCloseTo(takeHome, 2);
  });
});

describe("marginalTaxOnExtra", () => {
  it("matches the original engine for a gradual equity sale on top of salary", () => {
    expect(marginalTaxOnExtra(70000, 17500)).toBeCloseTo(7350, 2);
  });

  it("returns 0 for non-positive extra", () => {
    expect(marginalTaxOnExtra(70000, 0)).toBe(0);
    expect(marginalTaxOnExtra(70000, -100)).toBe(0);
  });
});

describe("incomeTaxOnly", () => {
  it("matches calcTax's tax component exactly, with no NI deducted", () => {
    // Same band logic as calcTax, just without NI — pension/DB/State Pension income isn't
    // NI-liable in the UK. Reuses calcTax's own golden values (tax component only) above.
    expect(incomeTaxOnly(30000)).toEqual({ tax: 3486, takeHome: 26514 });
    expect(incomeTaxOnly(70000).tax).toBeCloseTo(15432, 2);
    expect(incomeTaxOnly(70000).takeHome).toBeCloseTo(54568, 2);
  });

  it("returns zero tax for non-positive gross", () => {
    expect(incomeTaxOnly(0)).toEqual({ tax: 0, takeHome: 0 });
  });
});

describe("marginalIncomeTaxOnly", () => {
  it("taxes a pension withdrawal's taxable slice at the payer's marginal rate, no NI", () => {
    // £12,570 of DB pension already uses up the personal allowance exactly, so every pound
    // of a pension withdrawal stacked on top is taxed at the basic rate (20%), not NI'd.
    expect(marginalIncomeTaxOnly(12570, 10000)).toBeCloseTo(2000, 2);
  });

  it("returns 0 for non-positive extra", () => {
    expect(marginalIncomeTaxOnly(12570, 0)).toBe(0);
  });
});

describe("grossUpTaxableWithdrawal", () => {
  it("grosses up a pension withdrawal so the net proceeds (after tax on the 75% taxable slice) meet netNeeded", () => {
    // No other taxable income, so the withdrawal alone uses the personal allowance.
    // 25% of the gross is tax-free; the rest is taxed as it stacks up through the bands.
    const { drawn, net } = grossUpTaxableWithdrawal(1_000_000, 20000, 0, 0.25);
    expect(net).toBeCloseTo(20000, 2);
    // Verify the number is internally consistent: draw the same amount and re-derive net.
    const taxableSlice = drawn * 0.75;
    const tax = marginalIncomeTaxOnly(0, taxableSlice);
    expect(drawn - tax).toBeCloseTo(20000, 2);
  });

  it("caps at the pot balance and reports the (lower) net it actually yields when the pot can't cover netNeeded", () => {
    const result = grossUpTaxableWithdrawal(5000, 20000, 0, 0.25);
    expect(result.drawn).toBe(5000);
    expect(result.net).toBeLessThan(20000);
    expect(result.net).toBeGreaterThan(0);
  });

  it("returns zero for an empty pot or a non-positive need", () => {
    expect(grossUpTaxableWithdrawal(0, 20000, 0, 0.25)).toEqual({ drawn: 0, net: 0 });
    expect(grossUpTaxableWithdrawal(10000, 0, 0, 0.25)).toEqual({ drawn: 0, net: 0 });
  });

  it("needs a bigger gross withdrawal to net the same amount when other taxable income already fills the basic-rate band", () => {
    const noOtherIncome = grossUpTaxableWithdrawal(1_000_000, 15000, 0, 0.25);
    const stackedOnDbPension = grossUpTaxableWithdrawal(1_000_000, 15000, 40000, 0.25);
    expect(stackedOnDbPension.drawn).toBeGreaterThan(noOtherIncome.drawn);
  });
});
