import { describe, expect, it } from "vitest";
import { calcTax, marginalTaxOnExtra } from "../tax";

// Golden values generated by running the original uk_fire_calculator.html engine
// functions verbatim in Node — see plan for methodology.
describe("calcTax", () => {
  it.each([
    [0, 0, 0, 0],
    [10000, 0, 0, 10000],
    [12570, 0, 0, 12570],
    [30000, 3486, 1394.4, 25119.6],
    [70000, 15432, 3410.6, 51157.4],
    [100000, 27432, 4010.6, 68557.4],
    [125140, 40002, 4513.4, 80624.6],
    [150000, 51189, 5010.6, 93800.4],
  ])("gross=%i -> tax=%f, ni=%f, takeHome=%f", (gross, tax, ni, takeHome) => {
    const result = calcTax(gross);
    expect(result.tax).toBeCloseTo(tax, 2);
    expect(result.ni).toBeCloseTo(ni, 2);
    expect(result.takeHome).toBeCloseTo(takeHome, 2);
  });
});

describe("marginalTaxOnExtra", () => {
  it("matches the original engine for a gradual equity sale on top of salary", () => {
    expect(marginalTaxOnExtra(70000, 17500)).toBeCloseTo(7350, 2);
  });

  it("returns 0 for non-positive extra", () => {
    expect(marginalTaxOnExtra(70000, 0)).toBe(0);
    expect(marginalTaxOnExtra(70000, -100)).toBe(0);
  });
});
